# Generated by Django 6.0.1 on 2026-01-27 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='boundary_coordinates',
            field=models.JSONField(blank=True, help_text='List of [lat, lng] coordinates for the boundary polygon', null=True),
        ),
    ]
