# Generated by Django 6.0.1 on 2026-01-29 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_boundary_coordinates'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSubsection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Main Stage, Food Court, VIP Area', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional details about this area')),
                ('boundary_coordinates', models.JSONField(help_text='Polygon coordinates for this subsection')),
                ('color', models.CharField(default='#ff7800', help_text='Hex color code for map display', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsections', to='events.event')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
